# Generated by Django 5.1.5 on 2025-02-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_y_apellido", models.CharField(max_length=100)),
                ("carrera", models.CharField(max_length=100)),
                ("promedio", models.DecimalField(decimal_places=2, max_digits=4)),
                ("semestres_cursados", models.IntegerField()),
                ("correo", models.EmailField(max_length=254)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Mujer")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_y_apellido", models.CharField(max_length=100)),
                ("asignatura", models.CharField(max_length=100)),
                ("tiempo_exp", models.IntegerField()),
                ("trayectoria_resumen", models.TextField(blank=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Mujer")], max_length=1
                    ),
                ),
            ],
        ),
    ]
